version: "3.9"
services:
  cribbage:
    build: ./server
    image: jones:cribbage
    environment: 
      - CRIBBAGE_SERVER_PORT=${CRIBBAGE_SERVER_PORT}
    deploy:
      mode: replicated
      replicas: ${CRIBBAGE_SERVERS}
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cribbage
    ports:
      - "4000:4000"